name: 'issue-list-action'
description: 'issue-list-action'
inputs:
  githubToken: 
    description: 'GITHUB_TOKEN'
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'node16'
  main: 'index.js'
  