name: 'issue-list-action'
description: 'issue-list-action'
inputs:
  githubToken: 
    description: 'GITHUB_TOKEN'
    default: ${{ secrets.GITHUB_TOKEN }}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'
  