name: 'issue-blog-action'
author: 'Bpazy'
description: 'Update issue blog to README'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  COMMIT_MSG:
    description: 'message when update issue activity'
    required: false
    default: 'Update README with the recent issue activity'
  NUMBER:
    description: 'issues number. Max: 100'
    required: false
    default: 20
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: blue
