name: 'issue-blog-action'
author: 'Bpazy'
description: 'Update issue blog to README'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  COMMIT_MSG:
    description: 'message when update issue activity'
    required: false
    default: 'Update README with the recent issue activity'
  NUMBER:
    description: 'issues number. Max: 100'
    required: false
    default: '20'
  SUMMARY_LENGTH:
    description: 'Summary default char length'
    required: false
    default: '100'
  OWNER:
    description: 'github owner. Such as "Bpazy"'
    required: false
  REPO:
    description: 'github repo. Such as "issue-list-action"'
    required: false
  GITHUB_NAME:
    description: 'Your Github name, used to commit when Github Action running'
    required: false
    default: ''
  GITHUB_EMAIL:
    description: 'Your Github email, used to commit when Github Action running'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: blue
